version: 2.0

jobs:
  build_image:
    docker:
      - image: circleci/python:3.6-stretch
    working_directory: ~/conda-channel
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build docker image
          command: |
            SANITIZED_BRANCH=$(echo "$CIRCLE_BRANCH" | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9\.]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)
            docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
            docker pull quay.io/plotly/conda-channel:master || true
            docker pull quay.io/plotly/conda-channel:${SANITIZED_BRANCH} || true
            docker build -t quay.io/plotly/conda-channel:${SANITIZED_BRANCH} .
            docker push quay.io/plotly/conda-channel:${SANITIZED_BRANCH}

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_image